pipeline {
 
    agent any
 
    stages {
 
        stage('Checkout') {
            steps {
                echo 'Checking out source code'
                checkout scm
            }
        }
 
        stage('Build') {
            steps {
                echo 'Building project'
                bat '"C:\\Users\\athar\\Downloads\\apache-maven-3.9.16-bin\\apache-maven-3.9.16\\bin\\mvn.cmd" -f atharva\\pom.xml clean compile'
            }
        }
 
        stage('Run Selenium Tests') {
            steps {
                echo 'Running Selenium tests'
                bat '"C:\\Users\\athar\\Downloads\\apache-maven-3.9.16-bin\\apache-maven-3.9.16\\bin\\mvn.cmd" -f atharva\\pom.xml clean compile'
        }
    }
}
}
